# MySQL en Docker (0verpass)
jdbc.url=jdbc:mysql://localhost:3306/0verpass?useUnicode=true&characterEncoding=UTF-8&serverTimezone=America/Argentina/Buenos_Aires
jdbc.user=0verpass
jdbc.password=0verpass

# HikariCP (opcional)
jdbc.pool.size=5
